<?php

namespace Database\Seeders;

use App\Models\Industry;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class IndustrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ["id" => 1, "name" => "Vending Machines"],
            ["id" => 2, "name" => "Reciclaje"],
            ["id" => 3, "name" => "Sale"],
            ["id" => 4, "name" => "Autotive"],
            ["id" => 5, "name" => "Finance"],
            ["id" => 6, "name" => "3PL"],
            ["id" => 7, "name" => "Supply Chain"],
            ["id" => 8, "name" => "Contruction"],
            ["id" => 9, "name" => ""],
            ["id" => 10, "name" => "Aluminum"],
            ["id" => 11, "name" => "e-commerce"],
            ["id" => 12, "name" => "Beauty & Health"],
            ["id" => 13, "name" => "Warehouse"],
            ["id" => 14, "name" => "Technology"],
            ["id" => 15, "name" => "ecommerce"],
            ["id" => 16, "name" => "Food & Bevetrage"],
            ["id" => 17, "name" => "Lease"],
            ["id" => 18, "name" => "Furnirure"],
            ["id" => 19, "name" => "Recycling"],
            ["id" => 20, "name" => "Bienes y Consumo"],
            ["id" => 21, "name" => "Construccion"],
            ["id" => 22, "name" => "Health & Beauty"],
            ["id" => 23, "name" => "Filter"],
            ["id" => 24, "name" => "Optical"],
            ["id" => 25, "name" => "Cosmetics"],
            ["id" => 26, "name" => "Retail"],
            ["id" => 27, "name" => "Logistic"],
            ["id" => 28, "name" => "Furniture"],
            ["id" => 29, "name" => "Agroindustry"],
            ["id" => 30, "name" => "Appliance"],
            ["id" => 31, "name" => "Empaques de Espuma"],
            ["id" => 32, "name" => "Fitness"],
            ["id" => 33, "name" => "Fiber"],
            ["id" => 34, "name" => "Accessories"],
            ["id" => 35, "name" => "Construction"],
            ["id" => 36, "name" => "Glass"],
            ["id" => 37, "name" => "Wire & Cable"],
            ["id" => 38, "name" => "Plastic Injection"],
            ["id" => 39, "name" => "Telecommunications"],
            ["id" => 40, "name" => "Consumer Products"],
            ["id" => 41, "name" => "Painting"],
            ["id" => 42, "name" => "Printing"],
            ["id" => 43, "name" => "Montacargas"],
            ["id" => 44, "name" => "Mochilas"],
            ["id" => 45, "name" => "Sports"],
            ["id" => 46, "name" => "Chemical & Pharmaceutical"],
            ["id" => 47, "name" => "Call Center"],
            ["id" => 48, "name" => "Toys"],
            ["id" => 49, "name" => "Paint"],
            ["id" => 50, "name" => "HVAC"],
            ["id" => 51, "name" => "Aerospace"],
            ["id" => 52, "name" => "Energy"],
            ["id" => 53, "name" => "Forged Components"],
            ["id" => 54, "name" => "Pipes"],
            ["id" => 55, "name" => "Tractopartes"],
            ["id" => 56, "name" => "Shelter"],
            ["id" => 57, "name" => "Wind Energy"],
            ["id" => 58, "name" => "Medic"],
            ["id" => 59, "name" => "Injection"],
            ["id" => 60, "name" => "White Goods"],
            ["id" => 61, "name" => "fabrican espejos"],
            ["id" => 62, "name" => "Pallets"],
            ["id" => 63, "name" => "Doors & Windows"],
            ["id" => 64, "name" => "Steel"],
            ["id" => 65, "name" => "Candy"],
            ["id" => 66, "name" => "Esmaltes"],
            ["id" => 67, "name" => "Packaging"],
            ["id" => 68, "name" => "Textile"],
            ["id" => 69, "name" => "Medical"],
            ["id" => 70, "name" => "Sellos"],
            ["id" => 71, "name" => "Logistics"],
            ["id" => 72, "name" => "Metalmechanics"],
            ["id" => 73, "name" => "Food & Beverage"],
            ["id" => 74, "name" => "Plastics"],
            ["id" => 75, "name" => "Paper"],
            ["id" => 76, "name" => "Electric & Electronics"],
            ["id" => 77, "name" => "Lighting"],
            ["id" => 78, "name" => "Stamping"],
            ["id" => 79, "name" => "Furnitures"],
            ["id" => 80, "name" => "Automotive"],
            ["id" => 81, "name" => "Tuberias y Conexiones"],
            ["id" => 82, "name" => "Financial Services"],
            ["id" => 83, "name" => "Oiler"],
            ["id" => 84, "name" => "Office"],
            ["id" => 85, "name" => "Cable Wire"],
            ["id" => 86, "name" => "Q2 2017"],
            ["id" => 87, "name" => "Q2 2010"],
            ["id" => 88, "name" => "Q3 2018"],
            ["id" => 89, "name" => "Q4 2012"],
            ["id" => 90, "name" => "Q2 2022"],
            ["id" => 91, "name" => "Q4 2017"],
            ["id" => 92, "name" => "Q2 2020"],
            ["id" => 93, "name" => "TBD"],
            ["id" => 94, "name" => "Q4 2019"],
            ["id" => 95, "name" => "Q2 2021"],
            ["id" => 96, "name" => "Q1 2022"],
            ["id" => 97, "name" => "Q2 2016"],
            ["id" => 98, "name" => "Q2 2019"],
            ["id" => 99, "name" => "Q3 2014"],
            ["id" => 100, "name" => "Q2 2014"],
            ["id" => 101, "name" => "Q1 2020"],
            ["id" => 102, "name" => "Textiles"],
            ["id" => 103, "name" => "j"],
            ["id" => 104, "name" => "Water Solution"],
            ["id" => 105, "name" => "Machinery Tools"],
            ["id" => 106, "name" => "Plastic"],
            ["id" => 107, "name" => "Sporting Goods"],
            ["id" => 108, "name" => "Agriculture"],
            ["id" => 109, "name" => "Printer"]
        ];


        Industry::insert($data);
    }
}
